version: '3.5'

services:
  traefik:
    image: traefik:alpine
    container_name: traefik
    command:
#     - --api
      - --logLevel=INFO
      - --defaultentrypoints=http,https
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --docker
      - --docker.exposedbydefault=false
      - --docker.domain=${DOCKER_DOMAIN}
      - --acme=false
      - --acme.acmelogging=true
      - --acme.email=${ACME_EMAIL}
      - --acme.storage=acme.json
      - --acme.entryPoint=https
      - --acme.onhostrule=true
      - --acme.httpchallenge=true
      - --acme.httpchallenge.entrypoint=http
#     - --acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
#   labels:
#     - traefik.enable=true
#     - traefik.backend=traefik
#     - traefik.port=8080
#     - traefik.frontend.rule=${TR_FE_RULE}
###   - traefik.frontend.entryPoints=http,https
    ports:
#     - 8080
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ${PERSISTENT_DIR}/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - commonnet

  dokuwiki:
    image: mtilson/dokuwiki:latest
    container_name: dokuwiki
    volumes:
      - ${PERSISTENT_DIR}/dokuwiki/data:/data
      - ${PERSISTENT_DIR}/dokuwiki/root/.ssh:/root/.ssh
    labels:
      - traefik.enable=true
      - traefik.backend=dokuwiki
      - traefik.port=80
      - traefik.frontend.rule=${DOKUWIKI_FE_RULE}
    environment:
      - BACKUP_USER_EMAIL
      - GIT_BACKUP_REPO_URL
      - TZ=${TZ-Europe/Luxembourg}
      - MEMORY_LIMIT
      - UPLOAD_MAX_SIZE
      - OPCACHE_MEM_SIZE
    restart: always
    networks:
      - commonnet

networks:
  commonnet:
    name: common-network
