version: '3.2'

services:
  traefik:
    image: traefik:alpine
    container_name: traefik
    command:
      - --logLevel=INFO
      - --defaultentrypoints=http,https
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --docker
      - --docker.exposedbydefault=false
      - --docker.domain=${DW_DOMAIN}
      - --acme=false
      - --acme.acmelogging=true
      - --acme.email=webmaster@${DW_DOMAIN}
      - --acme.storage=acme.json
      - --acme.entryPoint=https
      - --acme.onhostrule=true
      - --acme.httpchallenge=true
      - --acme.httpchallenge.entrypoint=http
#     - --acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ${DW_PERSISTENT_DIR}/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  dokuwiki:
    image: mtilson/dokuwiki:latest
    container_name: dokuwiki
    volumes:
      - ${DW_PERSISTENT_DIR}/data:/data
    labels:
      - traefik.enable=true
      - traefik.backend=dokuwiki
      - traefik.port=80
      - traefik.frontend.rule=${DW_FE_RULE}
    environment:
      - DW_DOMAIN=${DW_DOMAIN}
      - DW_BACKUP_GIT_REMOTE_URL=${DW_BACKUP_GIT_REMOTE_URL}
      - TZ=${TZ-Europe/Luxembourg}
      - MEMORY_LIMIT=${MEMORY_LIMIT}
      - UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE}
      - OPCACHE_MEM_SIZE=${OPCACHE_MEM_SIZE}
    restart: always
