version: '2.4'

services:
  dokuwiki:
    container_name: dokuwiki
    image: mtilson/dokuwiki:latest
    volumes:
      - ${PERSISTENT_DIR:-/opt/docker/persistent}/dokuwiki/data:/data
      - ${PERSISTENT_DIR:-/opt/docker/persistent}/dokuwiki/root/.ssh:/root/.ssh
    labels:
      - traefik.enable=true
      - traefik.backend=dokuwiki
      - traefik.port=80
      - traefik.frontend.rule=${DOKUWIKI_FE_RULE:-Host:wiki.example.com}
    environment:
      - BACKUP_USER_EMAIL=${BACKUP_USER_EMAIL:-dokuwiki-backup@example.com}
      - GIT_BACKUP_REPO_URL=${GIT_BACKUP_REPO_URL:-git@github.com:example/dokuwiki-backup.git}
      - TZ=${TZ:-Europe/Luxembourg}
      - MEMORY_LIMIT
      - UPLOAD_MAX_SIZE
      - OPCACHE_MEM_SIZE
    restart: always
    networks:
      - commonnet

networks:
  commonnet:
    external:
      name: ${COMMON_NETWORK:-traefik-public-network}
